
name: Go
on:
  push:
    # branches:
    #   - main
    tags:
      - v1.*.*
  pull_request:
    branches:
      - main

jobs:

  build:
    name: Build
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.17.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.17.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Test
      run: go test